# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 03:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='validity',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_hash',
            field=models.CharField(default='1234567', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='username',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
