# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0002_auto_20171017_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='sample_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
