# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0003_uploadfile_sample_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='sample_info',
            new_name='file_info',
        ),
    ]
