# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 08:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0005_projectqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile(b'^[\\w.@+-]+$'), 'Enter a valid username.', b'invalid')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='projectqueue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metDNACore.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_info',
            field=models.TextField(default=b'{}'),
        ),
        migrations.AlterUniqueTogether(
            name='projectqueue',
            unique_together=set([('user_id', 'project')]),
        ),
    ]
