# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 02:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0006_auto_20171031_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='polarity',
            field=models.CharField(default='NEG', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$', 32), 'Enter a valid username.', 'invalid')], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_info',
            field=models.TextField(default='{}'),
        ),
    ]
