# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0007_auto_20171115_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectqueue',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectqueue',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='uploadfile',
            unique_together=set([('project', 'file_name', 'polarity')]),
        ),
    ]
