# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metDNACore', '0009_auto_20171121_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_project',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
    ]
