export * from './introduction/introduction.component';
export * from './analysis/analysis.component';
export * from './help/help.component';
export * from './faq/faq.component';
export * from './log-in/log-in.component';
export * from './file-upload/file-upload.component';
export * from './analysis-para-setting/analysis-para-setting.component';
export * from './analysis-data-format/analysis-data-format.component';
export * from './demo/demo.component';